export {default as Home} from './Home/Home'
export {default as N5} from './N5/N5'
export {default as N4} from './N4/N4'
export {default as Result} from './Result/Result'
export {default as NotFound} from './NotFound/NotFound'